export const SEED_DATA = {
  checklists: [
    {
      id: 1,
      title: "SEO Master Checklist v2",
      version: "v2 integrated",
      source_type: "embedded",
      raw_content: "1. Старт, доступы, аналитика, baseline\n☐ 101. Соберите доступы к системам аналитики и панелям вебмастеров (GSC, Я.Вебмастер) — 🔴 Критично\n☐ 102. Установите счетчики Яндекс.Метрика и Google Analytics 4 — 🔴 Критично\n☐ 103. Настройте отслеживание электронной торговли (E-commerce аналитика) — 🟡 Важно\n\n2. Технический аудит, индексация, структура\n☐ 201. Проведите сканирование сайта краулером (Screaming Frog / Netpeak Spider) — 🔴 Критично\n☐ 202. Сформируйте правильный файл robots.txt для оптимизации краулингового бюджета — 🔴 Критично\n☐ 203. Настройте генерацию и обновление XML-карты сайта Sitemap.xml — 🔴 Критично\n\n3. Ниша, аудит бизнеса, ЦА и конкуренты\n☐ 301. Соберите список SEO-конкурентов и проведите анализ их видимости — 🔴 Критично\n☐ 302. Соберите полное семантическое ядро проекта — 🔴 Критично\n☐ 303. Проведите кластеризацию семантического ядра и создайте карту релевантности — 🟡 Важно\n\n4. On-page оптимизация, контент и коммерческие факторы\n☐ 401. Оптимизируйте шаблоны и ручные метатеги Title, Description, заголовки H1 — 🔴 Критично\n☐ 402. Проведите аудит и оптимизацию коммерческих факторов ранжирования — 🟡 Важно\n\n5. E-E-A-T, локальное SEO, репутация и SERM\n☐ 501. Настройте и оптимизируйте карточку компании в Яндекс.Бизнес и Google Business Profile — 🟡 Важно\n☐ 502. Анализируйте E-E-A-T (Экспертность, Авторитетность, Достоверность) факторы — 🟡 Важно\n\n6. Контроль внедрения, аналитика и корректировка стратегии\n☐ 601. Проведите итоговую повторную диагностику технического состояния и позиций — 🔴 Критично",
      task_count: 14,
      status: "normalized",
      created_at: "2026-05-22T02:26:27.907Z",
      updated_at: "2026-05-22T02:26:27.907Z"
    }
  ],
  tasks: [
    {
      id: 101,
      checklist_id: 1,
      section: "1. Старт, доступы, аналитика, baseline",
      raw_task: "Соберите доступы к системам аналитики и панелям вебмастеров (GSC, Я.Вебмастер)",
      priority: "Критично",
      default_month: 1,
      work_block: "Доступы и старт",
      work_type: "Аудит прав",
      process_text: "Запрос доступов у клиента → проверка делегированных прав → настройка гостевого доступа для команды",
      result_text: "Настроенный и проверенный рабочий доступы в кабинеты вебмастеров",
      artifact_type: "Таблица доступов",
      contract_text: "Аудит доступов и настройка гостевых прав в поисковом и аналитическом ПО.",
      client_text: "Мы получим и проверим ваши доступы в панели вебмастеров Яндекс и Google, чтобы работать безопасно.",
      internal_text: "Связаться с представителем проекта, получить доступы к GA4, Яндекс.Метрике, GSC и Я.Вебмастеру.",
      acceptance_criteria: "Таблица доступов заполнена, права проверены, все доступы активны.",
      responsible_role: "SEO-специалист",
      repeatability: "Разово",
      status: "normalized",
      created_at: "2026-05-22T02:26:27.907Z",
      updated_at: "2026-05-22T02:26:27.907Z",
      applicability: {
        id: 101,
        task_id: 101,
        applies_to_all: true,
        applies_to_ecommerce: false,
        applies_to_services: false,
        applies_to_local: false,
        applies_to_blog: false,
        applies_to_ymyl: false,
        requires_catalog: false,
        requires_filters: false,
        requires_multilingual: false,
        requires_migration: false,
        requires_local_business: false,
        exclude_if_no_blog: false,
        exclude_if_no_ecommerce: false,
        exclude_if_no_multilingual: false,
        exclude_if_no_local_seo: false
      }
    },
    {
      id: 102,
      checklist_id: 1,
      section: "1. Старт, доступы, аналитика, baseline",
      raw_task: "Установите счетчики Яндекс.Метрика и Google Analytics 4",
      priority: "Критично",
      default_month: 1,
      work_block: "Аналитика",
      work_type: "Интеграция",
      process_text: "Генерация JS-кода счетчиков → передача разработчику или интеграция через Google Tag Manager → проверка отправки просмотров",
      result_text: "Интегрированные системы аналитики без дублирования кодов счётчиков",
      artifact_type: "Кабинеты счетчиков",
      contract_text: "Размещение и настройка систем веб-аналитики на страницах сайта.",
      client_text: "Установим системы веб-аналитики на сайт, чтобы собирать точную информацию о посетителях.",
      internal_text: "Проверить код GA4 и Яндекс.Метрики. Внедрить через GTM или напрямую в head.",
      acceptance_criteria: "Счетчики корректно функционируют, трафик и визиты фиксируются в отчетах.",
      responsible_role: "Веб-аналитик",
      repeatability: "Разово",
      status: "normalized",
      created_at: "2026-05-22T02:26:27.907Z",
      updated_at: "2026-05-22T02:26:27.907Z",
      applicability: {
        id: 102,
        task_id: 102,
        applies_to_all: true,
        applies_to_ecommerce: false,
        applies_to_services: false,
        applies_to_local: false,
        applies_to_blog: false,
        applies_to_ymyl: false,
        requires_catalog: false,
        requires_filters: false,
        requires_multilingual: false,
        requires_migration: false,
        requires_local_business: false,
        exclude_if_no_blog: false,
        exclude_if_no_ecommerce: false,
        exclude_if_no_multilingual: false,
        exclude_if_no_local_seo: false
      }
    },
    {
      id: 103,
      checklist_id: 1,
      section: "1. Старт, доступы, аналитика, baseline",
      raw_task: "Настройте отслеживание электронной торговли (E-commerce аналитика)",
      priority: "Важно",
      default_month: 1,
      work_block: "Аналитика",
      work_type: "Настройка целей",
      process_text: "Проектирование dataLayer для событий purchase и add_to_cart → конфигурация GA4/Yandex Commerce → тестовый заказ",
      result_text: "Настроенное корректное отслеживание транзакций, выручки и популярных товаров в аналитике",
      artifact_type: "Отчёты e-commerce",
      contract_text: "Настройка отслеживания электронной торговли и транзакций проекта в GA4 и Яндекс.Метрике.",
      client_text: "Настроим сбор данных о покупках, чтобы вы видели реальную выручку и окупаемость SEO.",
      internal_text: "Внедрить ТЗ на dataLayer для e-commerce, проверить отправку событий корзины, чекаута и покупки.",
      acceptance_criteria: "Отчеты аналитики фиксируют суммы транзакций и перечень купленных товаров без расхождений.",
      responsible_role: "Веб-аналитик",
      repeatability: "Разово",
      status: "normalized",
      created_at: "2026-05-22T02:26:27.907Z",
      updated_at: "2026-05-22T02:26:27.907Z",
      applicability: {
        id: 103,
        task_id: 103,
        applies_to_all: true,
        applies_to_ecommerce: true,
        applies_to_services: false,
        applies_to_local: false,
        applies_to_blog: false,
        applies_to_ymyl: false,
        requires_catalog: true,
        requires_filters: false,
        requires_multilingual: false,
        requires_migration: false,
        requires_local_business: false,
        exclude_if_no_blog: false,
        exclude_if_no_ecommerce: false,
        exclude_if_no_multilingual: false,
        exclude_if_no_local_seo: false
      }
    },
    {
      id: 201,
      checklist_id: 1,
      section: "2. Технический аудит, индексация, структура",
      raw_task: "Проведите сканирование сайта краулером (Screaming Frog / Netpeak Spider)",
      priority: "Критично",
      default_month: 2,
      work_block: "Технический аудит",
      work_type: "Краулинг",
      process_text: "Настройка параметров сканирования → полный обход сайта → выгрузка логов сканирования и ошибок индексации",
      result_text: "Лог сканирования сайта с выявленными ошибками в кодах ответов",
      artifact_type: "Файл выгрузки краулера",
      contract_text: "Первичное полное техническое сканирование сайта для оценки доступности страниц.",
      client_text: "Мы просканируем ваш сайт специальным роботом, имитируя поведение поисковых систем, для поиска скрытых ошибок.",
      internal_text: "Запустить сканирование Screaming Frog, проанализировать отчет по кодам ответов сервера.",
      acceptance_criteria: "Технический отчет о сканировании сохранен, все битые ссылки выявлены.",
      responsible_role: "SEO-специалист",
      repeatability: "Ежемесячно",
      status: "normalized",
      created_at: "2026-05-22T02:26:27.907Z",
      updated_at: "2026-05-22T02:26:27.907Z",
      applicability: {
        id: 201,
        task_id: 201,
        applies_to_all: true,
        applies_to_ecommerce: false,
        applies_to_services: false,
        applies_to_local: false,
        applies_to_blog: false,
        applies_to_ymyl: false,
        requires_catalog: false,
        requires_filters: false,
        requires_multilingual: false,
        requires_migration: false,
        requires_local_business: false,
        exclude_if_no_blog: false,
        exclude_if_no_ecommerce: false,
        exclude_if_no_multilingual: false,
        exclude_if_no_local_seo: false
      }
    },
    {
      id: 202,
      checklist_id: 1,
      section: "2. Технический аудит, индексация, структура",
      raw_task: "Сформируйте правильный файл robots.txt для оптимизации краулингового бюджета",
      priority: "Критично",
      default_month: 2,
      work_block: "Индексация",
      work_type: "Настройки robots",
      process_text: "Анализ текущего robots.txt → закрытие системных папок и дублей → настройка директив Disallow и сопоставление Sitemap",
      result_text: "Оптимизированный файл robots.txt в корне сайта, защищающий служебные разделы от индексации",
      artifact_type: "Поисковый файл robots.txt",
      contract_text: "Формирование корректирующего файла robots.txt для управления поведением поисковых роботов.",
      client_text: "Создадим инструкцию для роботов, которая закроет от них мусорные файлы и ускорит индексацию важных страниц.",
      internal_text: "Сформировать robots.txt, закрыть страницы фильтрации без ЧПУ, корзину, личный кабинет, админку. Указать путь к Sitemap.",
      acceptance_criteria: "Файл robots.txt доступен по адресу site.ru/robots.txt, Яндекс и Google считывают директивы корректно.",
      responsible_role: "SEO-специалист",
      repeatability: "Разово",
      status: "normalized",
      created_at: "2026-05-22T02:26:27.907Z",
      updated_at: "2026-05-22T02:26:27.907Z",
      applicability: {
        id: 202,
        task_id: 202,
        applies_to_all: true,
        applies_to_ecommerce: false,
        applies_to_services: false,
        applies_to_local: false,
        applies_to_blog: false,
        applies_to_ymyl: false,
        requires_catalog: false,
        requires_filters: false,
        requires_multilingual: false,
        requires_migration: false,
        requires_local_business: false,
        exclude_if_no_blog: false,
        exclude_if_no_ecommerce: false,
        exclude_if_no_multilingual: false,
        exclude_if_no_local_seo: false
      }
    },
    {
      id: 203,
      checklist_id: 1,
      section: "2. Технический аудит, индексация, структура",
      raw_task: "Настройте генерацию и обновление XML-карты сайта Sitemap.xml",
      priority: "Критично",
      default_month: 2,
      work_block: "Индексация",
      work_type: "Настройки sitemap",
      process_text: "Исключение неиндексируемых страниц → настройка автоматической генерации XML → проверка валидности в вебмастерах",
      result_text: "Регулярно обновляемый XML-файл карты сайта со списком только канонических страниц со статусом 200 OK",
      artifact_type: "Файл Sitemap.xml",
      contract_text: "Внедрение и проверка XML-карты сайта для ускорения индексации структуры.",
      client_text: "Настроим автоматическую карту сайта (Sitemap), по которой поисковики мгновенно увидят все новые товары и статьи.",
      internal_text: "Исключить из sitemap.xml редиректы, битые страницы, неканонические URL. Добавить адрес в вебмастерские панели.",
      acceptance_criteria: "Файл валидирован, загружен в кабинеты вебмастеров без предупреждений и содержит целевые URL.",
      responsible_role: "SEO-специалист",
      repeatability: "При изменениях",
      status: "normalized",
      created_at: "2026-05-22T02:26:27.907Z",
      updated_at: "2026-05-22T02:26:27.907Z",
      applicability: {
        id: 203,
        task_id: 203,
        applies_to_all: true,
        applies_to_ecommerce: false,
        applies_to_services: false,
        applies_to_local: false,
        applies_to_blog: false,
        applies_to_ymyl: false,
        requires_catalog: false,
        requires_filters: false,
        requires_multilingual: false,
        requires_migration: false,
        requires_local_business: false,
        exclude_if_no_blog: false,
        exclude_if_no_ecommerce: false,
        exclude_if_no_multilingual: false,
        exclude_if_no_local_seo: false
      }
    },
    {
      id: 301,
      checklist_id: 1,
      section: "3. Ниша, аудит бизнеса, ЦА и конкуренты",
      raw_task: "Соберите список SEO-конкурентов и проведите анализ их видимости",
      priority: "Критично",
      default_month: 3,
      work_block: "Анализ конкурентов",
      work_type: "Маркетинговый анализ",
      process_text: "Опрос клиента → выгрузка сайтов с пересекающейся семантикой из Keys.so / Serpstat → оценка трафика и видимости",
      result_text: "Сводная таблица ключевых органических конкурентов с оценкой их показателей",
      artifact_type: "Таблица сравнительного анализа",
      contract_text: "Маркетинговый аудит видимости основных веб-конкурентов.",
      client_text: "Проведем детальный анализ конкурентов в выдаче, выявим их сильные и слабые стороны для построения нашей стратегии.",
      internal_text: "Собрать 5-10 топовых конкурентов в нише, проанализировать их ИКС, посещаемость, количество ключевых слов в ТОП-10.",
      acceptance_criteria: "Таблица сравнения конкурентов заполнена, сделаны ключевые выводы по сильным сторонам лидеров.",
      responsible_role: "SEO-аналитик",
      repeatability: "Разово",
      status: "normalized",
      created_at: "2026-05-22T02:26:27.907Z",
      updated_at: "2026-05-22T02:26:27.907Z",
      applicability: {
        id: 301,
        task_id: 301,
        applies_to_all: true,
        applies_to_ecommerce: false,
        applies_to_services: false,
        applies_to_local: false,
        applies_to_blog: false,
        applies_to_ymyl: false,
        requires_catalog: false,
        requires_filters: false,
        requires_multilingual: false,
        requires_migration: false,
        requires_local_business: false,
        exclude_if_no_blog: false,
        exclude_if_no_ecommerce: false,
        exclude_if_no_multilingual: false,
        exclude_if_no_local_seo: false
      }
    },
    {
      id: 302,
      checklist_id: 1,
      section: "3. Ниша, аудит бизнеса, ЦА и конкуренты",
      raw_task: "Соберите полное семантическое ядро проекта",
      priority: "Критично",
      default_month: 3,
      work_block: "Семантика",
      work_type: "Сбор семантики",
      process_text: "Сбор маркерных запросов → парсинг через Key Collector поисковых подсказок → чистка мусора и минус-слов → кластеризация по интенту",
      result_text: "Структурированное семантическое ядро с распределением запросов по кластерам",
      artifact_type: "Таблица семантического ядра",
      contract_text: "Проектирование и группировка семантического ядра органических запросов.",
      client_text: "Соберем поисковые запросы, по которым ваши клиенты ищут товары или услуги, и распределим их по страницам.",
      internal_text: "Собрать маркерные запросы, запустить сбор левой и правой колонок Яндекс Wordstat, очистить нецелевые ключевики.",
      acceptance_criteria: "Семантическое ядро содержит запросы, частотности, интенты и кластерную структуру, готовую к внедрению.",
      responsible_role: "SEO-специалист",
      repeatability: "Разово",
      status: "normalized",
      created_at: "2026-05-22T02:26:27.907Z",
      updated_at: "2026-05-22T02:26:27.907Z",
      applicability: {
        id: 302,
        task_id: 302,
        applies_to_all: true,
        applies_to_ecommerce: false,
        applies_to_services: false,
        applies_to_local: false,
        applies_to_blog: false,
        applies_to_ymyl: false,
        requires_catalog: false,
        requires_filters: false,
        requires_multilingual: false,
        requires_migration: false,
        requires_local_business: false,
        exclude_if_no_blog: false,
        exclude_if_no_ecommerce: false,
        exclude_if_no_multilingual: false,
        exclude_if_no_local_seo: false
      }
    },
    {
      id: 303,
      checklist_id: 1,
      section: "3. Ниша, аудит бизнеса, ЦА и конкуренты",
      raw_task: "Проведите кластеризацию семантического ядра и создайте карту релевантности",
      priority: "Важно",
      default_month: 3,
      work_block: "Семантика",
      work_type: "Кластеризация",
      process_text: "Группировка запросов на основе ТОП поиска → распределение кластеров по текущим и новым URL → сопоставление посадочных страниц",
      result_text: "Утвержденная карта релевантности (запросы-страницы) для оптимизации метатегов и контента",
      artifact_type: "Интерактивная карта релевантности (XLSX)",
      contract_text: "Кластеризация собранных ключевых запросов и проектирование посадочных URL.",
      client_text: "Сгруппируем фразы по смыслу и определим, под какой запрос какую страницу развивать или создавать с нуля.",
      internal_text: "Сгруппировать ядро по ТОП-10 совпадениям (софт-кластеризация), прикрепить группы к посадочным иерархиям.",
      acceptance_criteria: "Карта релевантности сопоставляет каждую целевую фразу конкретному URL-адресу без конфликтов.",
      responsible_role: "SEO-специалист",
      repeatability: "Разово",
      status: "normalized",
      created_at: "2026-05-22T02:26:27.907Z",
      updated_at: "2026-05-22T02:26:27.907Z",
      applicability: {
        id: 303,
        task_id: 303,
        applies_to_all: true,
        applies_to_ecommerce: false,
        applies_to_services: false,
        applies_to_local: false,
        applies_to_blog: false,
        applies_to_ymyl: false,
        requires_catalog: false,
        requires_filters: false,
        requires_multilingual: false,
        requires_migration: false,
        requires_local_business: false,
        exclude_if_no_blog: false,
        exclude_if_no_ecommerce: false,
        exclude_if_no_multilingual: false,
        exclude_if_no_local_seo: false
      }
    },
    {
      id: 401,
      checklist_id: 1,
      section: "4. On-page оптимизация, контент и коммерческие факторы",
      raw_task: "Оптимизируйте шаблоны и ручные метатеги Title, Description, заголовки H1",
      priority: "Критично",
      default_month: 4,
      work_block: "On-page",
      work_type: "Метатеги",
      process_text: "Составление формул автогенерации метатегов для карточек товара → ручное написание метатегов для приоритетных категорий на основе ядра",
      result_text: "Оптимизированные и привлекательные метатеги на страницах структуры с вхождением ключевых фраз",
      artifact_type: "ТЗ на внедрение метатегов",
      contract_text: "Комплексная оптимизация метаданных Title, Description и заголовков первого уровня H1.",
      client_text: "Напишем привлекательные заголовки (Title и Description) для страниц, чтобы повысить кликабельность в выдаче.",
      internal_text: "Сформировать оптимизированные теги, соблюдая длину и правила вхождения LSI/ключевых слов. Передать на внедрение.",
      acceptance_criteria: "Метатеги обновлены на боевом сайте, соответствуют семантическому ядру и не дублируются.",
      responsible_role: "SEO-специалист",
      repeatability: "Постоянно",
      status: "normalized",
      created_at: "2026-05-22T02:26:27.907Z",
      updated_at: "2026-05-22T02:26:27.907Z",
      applicability: {
        id: 401,
        task_id: 401,
        applies_to_all: true,
        applies_to_ecommerce: false,
        applies_to_services: false,
        applies_to_local: false,
        applies_to_blog: false,
        applies_to_ymyl: false,
        requires_catalog: false,
        requires_filters: false,
        requires_multilingual: false,
        requires_migration: false,
        requires_local_business: false,
        exclude_if_no_blog: false,
        exclude_if_no_ecommerce: false,
        exclude_if_no_multilingual: false,
        exclude_if_no_local_seo: false
      }
    },
    {
      id: 402,
      checklist_id: 1,
      section: "4. On-page оптимизация, контент и коммерческие факторы",
      raw_task: "Проведите аудит и оптимизацию коммерческих факторов ранжирования",
      priority: "Важно",
      default_month: 4,
      work_block: "Коммерческие факторы",
      work_type: "Аудит доверия",
      process_text: "Проверка наличия контактов, реквизитов, страниц оплаты, доставки, гарантий → сравнение с ТОП-10 конкурентов по чек-листу коммерции",
      result_text: "Отчет с подробным перечнем доработок для повышения конверсии и доверия Яндекса/Google",
      artifact_type: "Аудит коммерческих факторов",
      contract_text: "Анализ и подготовка ТЗ по улучшению продающих страниц и элементов доверия сайта.",
      client_text: "Проверим коммерческие разделы (контакты, доставка, гарантии) и дадим рекомендации, чтобы убедить клиентов покупать у вас.",
      internal_text: "Пройти по чек-листу коммерческих факторов Яндекса. Составить ТЗ на расширение блока контактов, реквизитов и форм.",
      acceptance_criteria: "ТЗ передано разработчику, внедрены недостающие коммерческие элементы.",
      responsible_role: "SEO-маркетолог",
      repeatability: "Разово",
      status: "normalized",
      created_at: "2026-05-22T02:26:27.907Z",
      updated_at: "2026-05-22T02:26:27.907Z",
      applicability: {
        id: 402,
        task_id: 402,
        applies_to_all: true,
        applies_to_ecommerce: true,
        applies_to_services: false,
        applies_to_local: false,
        applies_to_blog: false,
        applies_to_ymyl: false,
        requires_catalog: true,
        requires_filters: false,
        requires_multilingual: false,
        requires_migration: false,
        requires_local_business: false,
        exclude_if_no_blog: false,
        exclude_if_no_ecommerce: false,
        exclude_if_no_multilingual: false,
        exclude_if_no_local_seo: false
      }
    },
    {
      id: 501,
      checklist_id: 1,
      section: "5. E-E-A-T, локальное SEO, репутация и SERM",
      raw_task: "Настройте и оптимизируйте карточку компании в Яндекс.Бизнес и Google Business Profile",
      priority: "Важно",
      default_month: 5,
      work_block: "Локальное SEO",
      work_type: "Карточки геосервисов",
      process_text: "Заполнение визитки компании фотографиями, графиком работ, услугами → сбор верификационного кода → оптимизация по семантике категорий",
      result_text: "Подтвержденные и оптимизированные профили компании на Яндекс.Картах и Google Maps",
      artifact_type: "Личные кабинеты геосервисов",
      contract_text: "Оптимизация представленности бизнеса на картах и в локальном поиске.",
      client_text: "Создадим и настроим профили вашей компании на Яндекс.Картах и Google Maps, чтобы прилечь клиентов из вашего района.",
      internal_text: "Заполнить профили на 100%, добавить прайс-лист/товары, ключевые слова в описание. Подтвердить права собственности.",
      acceptance_criteria: "Кабинеты активны, отображаются на картах, информация о компании актуальна и синхронизирована.",
      responsible_role: "SEO-специалист",
      repeatability: "Ежемесячно",
      status: "normalized",
      created_at: "2026-05-22T02:26:27.907Z",
      updated_at: "2026-05-22T02:26:27.907Z",
      applicability: {
        id: 501,
        task_id: 501,
        applies_to_all: true,
        applies_to_ecommerce: false,
        applies_to_services: false,
        applies_to_local: true,
        applies_to_blog: false,
        applies_to_ymyl: false,
        requires_catalog: false,
        requires_filters: false,
        requires_multilingual: false,
        requires_migration: false,
        requires_local_business: true,
        exclude_if_no_blog: false,
        exclude_if_no_ecommerce: false,
        exclude_if_no_multilingual: false,
        exclude_if_no_local_seo: false
      }
    },
    {
      id: 502,
      checklist_id: 1,
      section: "5. E-E-A-T, локальное SEO, репутация и SERM",
      raw_task: "Анализируйте E-E-A-T (Экспертность, Авторитетность, Достоверность) факторы",
      priority: "Важно",
      default_month: 5,
      work_block: "E-E-A-T",
      work_type: "Аудит экспертности",
      process_text: "Проверка профилей авторов статей, дипломов врачей/юристов, сертификатов продукции, политики конфиденциальности",
      result_text: "Перечень рекомендаций по улучшению E-E-A-T факторов под требования Google",
      artifact_type: "Документ рекомендаций E-E-A-T",
      contract_text: "Аудит факторов авторитетности и экспертности контента (E-E-A-T).",
      client_text: "Внедрим блоки доверия, подтверждения авторитетности авторов и сертификаты, что критически важно для продвижения в Google.",
      internal_text: "Добавить страницы авторов, информацию о рецензентах, ссылки на лицензии, актуализировать пользовательское соглашение.",
      acceptance_criteria: "Рекомендации внедрены, на медицинских/юридических статьях присутствуют ссылки на реальных экспертов.",
      responsible_role: "SEO-аналитик",
      repeatability: "Разово",
      status: "normalized",
      created_at: "2026-05-22T02:26:27.907Z",
      updated_at: "2026-05-22T02:26:27.907Z",
      applicability: {
        id: 502,
        task_id: 502,
        applies_to_all: true,
        applies_to_ecommerce: false,
        applies_to_services: false,
        applies_to_local: false,
        applies_to_blog: false,
        applies_to_ymyl: true,
        requires_catalog: false,
        requires_filters: false,
        requires_multilingual: false,
        requires_migration: false,
        requires_local_business: false,
        exclude_if_no_blog: false,
        exclude_if_no_ecommerce: false,
        exclude_if_no_multilingual: false,
        exclude_if_no_local_seo: false
      }
    },
    {
      id: 601,
      checklist_id: 1,
      section: "6. Контроль внедрения, аналитика и корректировка стратегии",
      raw_task: "Проведите итоговую повторную диагностику технического состояния и позиций",
      priority: "Критично",
      default_month: 6,
      work_block: "Аналитика",
      work_type: "Повторная диагностика",
      process_text: "Снятие финального среза позиций → сравнение с baseline первого месяца → повторный технический аудит краулером",
      result_text: "Сводный отчет о росте позиций, трафике и закрытых технических ошибках за 6 месяцев",
      artifact_type: "Отчет о динамике SEO-показателей",
      contract_text: "Мониторинг эффективности проведенных работ и контрольное сканирование сайта.",
      client_text: "Мы подведем итоги полугодового продвижения, замерим рост позиций в поиске и спланируем дальнейшее развитие сайта.",
      internal_text: "Сформировать таблицу сравнения позиций, провести финальный краулинг, оценить снижение процента дублей и ошибок.",
      acceptance_criteria: "Подготовлен наглядный итоговый отчет с графиками динамики видимости и планом на следующий период.",
      responsible_role: "Leading SEO Specialist",
      repeatability: "Разово",
      status: "normalized",
      created_at: "2026-05-22T02:26:27.907Z",
      updated_at: "2026-05-22T02:26:27.907Z",
      applicability: {
        id: 601,
        task_id: 601,
        applies_to_all: true,
        applies_to_ecommerce: false,
        applies_to_services: false,
        applies_to_local: false,
        applies_to_blog: false,
        applies_to_ymyl: false,
        requires_catalog: false,
        requires_filters: false,
        requires_multilingual: false,
        requires_migration: false,
        requires_local_business: false,
        exclude_if_no_blog: false,
        exclude_if_no_ecommerce: false,
        exclude_if_no_multilingual: false,
        exclude_if_no_local_seo: false
      }
    }
  ],
  projects: [
    {
      id: 1,
      name: "Интернет-магазин мебели (FurniStore)",
      site_url: "furnistore-mock.ru",
      site_type: "ecommerce",
      niche: "Мебель и интерьер",
      geography: "Москва, РФ",
      budget_level: "standard",
      duration_months: 6,
      has_catalog: true,
      has_blog: true,
      has_filters: true,
      has_ecommerce: true,
      has_local_seo: true,
      has_multilingual: false,
      has_ymyl: false,
      has_migration: false,
      created_at: "2026-05-22T02:26:27.907Z",
      updated_at: "2026-05-22T02:26:27.907Z"
    },
    {
      id: 2,
      name: "Юридические услуги (Правовед)",
      site_url: "pravoved-law.ru",
      site_type: "services",
      niche: "Юриспруденция и консалтинг",
      geography: "Санкт-Петербург, РФ",
      budget_level: "basic",
      duration_months: 6,
      has_catalog: false,
      has_blog: false,
      has_filters: false,
      has_ecommerce: false,
      has_local_seo: true,
      has_multilingual: false,
      has_ymyl: true,
      has_migration: false,
      created_at: "2026-05-22T02:26:27.907Z",
      updated_at: "2026-05-22T02:26:27.907Z"
    }
  ],
  llm_providers: [
    {
      id: 1,
      provider_name: "Gemini",
      api_endpoint: "https://generativelanguage.googleapis.com",
      api_key_encrypted: "AUTO_ENV_KEY",
      default_model: "gemini-3.5-flash",
      temperature: 0.3,
      max_tokens: 8000,
      is_active: true,
      created_at: "2026-05-22T02:26:27.907Z",
      updated_at: "2026-05-22T02:26:27.907Z"
    }
  ],
  generated_scopes: []
};
